# Q1: Import numpy library

In [1]:
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [3]:
sequence = np.linspace(0, 1, 15)
print(sequence)

[0.         0.07142857 0.14285714 0.21428571 0.28571429 0.35714286
 0.42857143 0.5        0.57142857 0.64285714 0.71428571 0.78571429
 0.85714286 0.92857143 1.        ]


# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [4]:
Array = np.array([[[1.1, 2.1, 3.1], [4.1, 5.1, 6.1]],
                [[7.1, 8.1, 9.1], [10.1, 11.1, 12.1]]])

print(Array)

[[[ 1.1  2.1  3.1]
  [ 4.1  5.1  6.1]]

 [[ 7.1  8.1  9.1]
  [10.1 11.1 12.1]]]


# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [8]:
print("Array's type:", type(Array))
print("Array's elements datatype:", Array.dtype)
print("Array's shape:", Array.shape)
print("Array's size:", Array.size)
print("Array's dimension:", Array.ndim)

Array's type: <class 'numpy.ndarray'>
Array's elements datatype: float64
Array's shape: (2, 2, 3)
Array's size: 12
Array's dimension: 3


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [9]:
newArray1 = Array.reshape(1, 2, 2, 3)
print("New array's shape:", newArray1.shape)
print("New array's dimension:", newArray1.ndim)

New array's shape: (1, 2, 2, 3)
New array's dimension: 4


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [11]:
int_array = newArray1.astype(int)
print(int_array)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]


# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [24]:
for element in np.nditer(int_array):
    print(element, end=' ')


1 2 3 4 5 6 7 8 9 10 11 12 

# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [25]:
print(int_array[1, 0, 1])

IndexError: index 1 is out of bounds for axis 0 with size 1

# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [26]:
print(int_array[1, 0, 2])
print(int_array[1, 1, 0])

IndexError: index 1 is out of bounds for axis 0 with size 1

# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [27]:
search = np.where(int_array == 8)
print("index of number 8: ", search)


index of number 8:  (array([0], dtype=int64), array([1], dtype=int64), array([0], dtype=int64), array([1], dtype=int64))


# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [29]:
reshapedArray = int_array.reshape(2, 3, 2)
print(reshapedArray)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [30]:
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

result = np.concatenate((arr1, arr2))
print(result)

[['A' 'B']
 ['E' 'F']
 ['C' 'D']
 ['G' 'H']]


# Q12.2: Join the arrays along rows with axis = 1 

In [15]:
rows = np.concatenate((

# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [32]:
split_result = np.split(result, 2, axis=1)
print(split_result[0])
print(split_result[1])

[['A']
 ['E']
 ['C']
 ['G']]
[['B']
 ['F']
 ['D']
 ['H']]
